# Generated by Django 4.2.5 on 2023-09-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_subjects_info_alter_semester_info_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_Subjects_Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_1', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_2', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_3', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_4', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_5', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_6', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_7', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_8', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('subject_9', models.CharField(blank=True, choices=[('THEORY', 'THEORY'), ('THOERY_LAB', 'THEORY_LAB'), ('WORKSHOP', 'WORKSHOP'), ('PRACTICAL', 'PRACTICAL'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('credit_hour_1', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_2', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_3', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_4', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_5', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_6', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_7', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_8', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('credit_hour_9', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=0, null=True)),
                ('obtained_marks_1', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_2', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_3', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_4', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_5', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_6', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_7', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_8', models.IntegerField(blank=True, default=0, null=True)),
                ('obtained_marks_9', models.IntegerField(blank=True, default=0, null=True)),
                ('total_marks_1', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_2', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_3', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_4', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_5', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_6', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_7', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_8', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
                ('total_marks_9', models.IntegerField(blank=True, choices=[(25, 25), (50, 50), (100, 100), (150, 150), (200, 200), (250, 250), (300, 300)], default=0, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subjects_info',
            options={'verbose_name': 'Semester_Subjects_Info', 'verbose_name_plural': "Semester_Subjects_Info's"},
        ),
        migrations.AlterField(
            model_name='semester_info',
            name='email',
            field=models.EmailField(default='xyz@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='semester_info',
            name='name',
            field=models.CharField(default='full name', max_length=80),
        ),
        migrations.AlterField(
            model_name='semester_info',
            name='roll_no',
            field=models.CharField(default='...@iub.edu.pk', max_length=100),
        ),
    ]
