# Generated by Django 4.2.5 on 2023-09-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_semester_last_cgpa_delete_subjects_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester_last_cgpa',
            name='last_semester_cgpa',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
