# Generated by Django 4.2.5 on 2023-09-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_semester_info_user_semester_last_cgpa_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester_info',
            name='user',
        ),
        migrations.RemoveField(
            model_name='semester_last_cgpa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='students_subjects_marks',
            name='user',
        ),
    ]
